# Generated by Django 4.0.3 on 2022-04-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useractivity_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(null=True)),
                ('logout_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usermaster_table',
            fields=[
                ('username', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('pass1', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('verified', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Userbase_table',
        ),
        migrations.DeleteModel(
            name='Usertransaction_table',
        ),
        migrations.AddField(
            model_name='useractivity_table',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.usermaster_table'),
        ),
    ]
