# Generated by Django 4.0.3 on 2022-04-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_useractivity_table_usermaster_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity_table',
            name='email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='host.usermaster_table'),
        ),
    ]
