# Generated by Django 4.0.3 on 2022-05-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='charging_mastertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Station_ID', models.CharField(max_length=50, null=True)),
                ('Txn_ID', models.IntegerField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='charging_transactiontable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Station_ID', models.IntegerField(max_length=50, null=True)),
                ('Local_IP', models.GenericIPAddressField()),
                ('Date_Time', models.DateTimeField(max_length=50, null=True)),
                ('Uptime', models.TimeField(max_length=50, null=True)),
                ('Relay_Status', models.IntegerField(max_length=50, null=True)),
                ('Station_Status', models.CharField(max_length=50, null=True)),
                ('Elapsed_Time', models.TimeField(max_length=50, null=True)),
                ('Amps', models.FloatField(max_length=50, null=True)),
                ('AC_Voltage', models.FloatField(max_length=50, null=True)),
                ('DC_Voltage', models.FloatField(max_length=50, null=True)),
                ('Temperature', models.FloatField(max_length=50, null=True)),
                ('Wattage', models.FloatField(max_length=50, null=True)),
                ('Free_Heap', models.IntegerField(max_length=50, null=True)),
                ('Last_KWH', models.FloatField(max_length=50, null=True)),
            ],
        ),
    ]
