# Generated by Django 4.0.3 on 2022-05-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charging_transactiontable',
            name='Date_Time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='charging_transactiontable',
            name='Elapsed_Time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='charging_transactiontable',
            name='Free_Heap',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='charging_transactiontable',
            name='Relay_Status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='charging_transactiontable',
            name='Station_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='charging_transactiontable',
            name='Uptime',
            field=models.TimeField(null=True),
        ),
    ]
