# Generated by Django 4.0.3 on 2022-05-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0002_alter_charging_transactiontable_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charging_mastertable',
            name='Txn_ID',
            field=models.IntegerField(null=True),
        ),
    ]
