# Generated by Django 4.0.3 on 2022-05-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0003_alter_charging_mastertable_txn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charging_mastertable',
            name='Station_ID',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='charging_mastertable',
            name='Txn_ID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='charging_transactiontable',
            name='Station_ID',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
