# Generated by Django 4.0.3 on 2022-05-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0005_alter_charging_mastertable_station_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charging_transactiontable',
            name='Elapsed_Time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
